// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwugfaukrvqsoxidlaeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3dWdmYXVrcnZxc294aWRsYWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjE3NDAsImV4cCI6MjA3NDM5Nzc0MH0.islpjmsy3wLp_9b473pStaWenKCp_rxuFDre4RSsPSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});